---
### Client ID
client_id: 
client_secret: 

scopes:
  - openid
  - profile
  - egovnrn

acr_values: "urn:be:fedict:iam:fas:citizen:Level300"

issuer: "https://idp.iamfas.ta.belgium.be/fas/oauth2"


# token_endpoint: "https://idp.iamfas.ta.belgium.be/fas/oauth2/access_token"
# authorize_endpoint:  "https://idp.iamfas.ta.belgium.be/fas/oauth2/authorize"
# userinfo_endpoint: "https://idp.iamfas.ta.belgium.be/fas/oauth2/userinfo"
# jwks_endpoint: 
token_signing_alg: "RS256"

skip_tls_verification: true
