# .github/workflows/release.yaml


name: Build and Release Binary


on: 
  release:
    types: [created]

jobs:

  build:

    if: contains(github.ref, 'v')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the binary
      run: make build-zip

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: project-binaries
        path: releases


  upload_assets:
    runs-on: ubuntu-latest

    needs: build

    strategy:
      matrix:
        os: [darwin_amd64, linux_amd64, windows_386, windows_amd64]
  
    steps:

    - name: Download built project binaries
      uses: actions/download-artifact@v2
      with:
        name: project-binaries

    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.2
      env:
        GITHUB_TOKEN: ${{ github.token }}


    ## Use with get_release
    - name: Upload Release Asset ${{ matrix.os }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }} 
        asset_path: ./oidc-client_${{ matrix.os }}.zip
        asset_name: oidc-client_${{ matrix.os }}.zip
        asset_content_type: application/zip